# Generated by Django 4.1.7 on 2023-04-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("expertise_forms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice", models.BooleanField()),
                ("box", models.BooleanField()),
                ("guarantee_term", models.IntegerField()),
                ("guarantee_term_type", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("microphone", models.BooleanField()),
                ("screen_size", models.IntegerField()),
                ("memory", models.IntegerField()),
                ("screen_type", models.CharField(max_length=50)),
                ("os_type", models.CharField(max_length=50)),
                ("os_type_compatiple", models.CharField(max_length=50)),
                ("screen_resolution", models.CharField(max_length=50)),
                ("cpu_frequency", models.IntegerField()),
                ("battery_capacity", models.IntegerField()),
                ("wifi", models.BooleanField()),
                ("speaker", models.BooleanField()),
                ("sim_support", models.BooleanField()),
                ("dust_proof", models.BooleanField()),
                ("nfc", models.BooleanField()),
                ("is_screen_has_broken_problem", models.BooleanField()),
                ("is_screen_has_obscuration_problem", models.BooleanField()),
                ("is_touch_screen_has_problem", models.BooleanField()),
                ("is_screen_has_dead_pixel", models.BooleanField()),
                ("is_device_has_case_problem", models.BooleanField()),
                ("is_speaker_has_problem", models.BooleanField()),
                ("is_power_button_has_problem", models.BooleanField()),
                ("is_battery_socket_has_problem", models.BooleanField()),
                ("is_device_has_freezing_problem", models.BooleanField()),
                ("is_bluetooth_has_problem", models.BooleanField()),
                ("is_wifi_has_problem", models.BooleanField()),
                ("is_microphone_has_problem", models.BooleanField()),
                ("is_device_has_cellular_problem", models.BooleanField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expertise_watch",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
