# Generated by Django 4.1.7 on 2023-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLetter',
            new_name='NewsLetter',
        ),
    ]
