# Generated by Django 4.1.7 on 2023-04-01 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                ("second_phone_number", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/reservations/"
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=150, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
