# Generated by Django 4.1.7 on 2023-04-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reservations"),
        ),
    ]
