# Generated by Django 4.1.7 on 2023-04-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0001_initial'),
        ('reservations', '0002_alter_reservation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_types.servicetype'),
            preserve_default=False,
        ),
    ]
