# Generated by Django 4.1.7 on 2023-04-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="techservice", name="brand",),
        migrations.RemoveField(model_name="techservice", name="device_type",),
    ]
